trigger:
- main  # Ana branch'ınız

pool:
  name: 'AWS'  # Agent Pool ismini burada yazıyoruz. EC2'yi eklediğimiz pool ismi bu olacak.

variables:
  remoteUser: 'ec2-user'  # EC2 kullanıcı adı
  remoteHost: '52.208.254.187'  # EC2 IP adresi

jobs:
- job: DeployToEC2
  displayName: 'Deploy to EC2 instance'
  steps:
    # Secure file kullanarak SSH anahtarını ayarlıyoruz
  - task: DownloadSecureFile@1
    name: downloadSSHKey
    inputs:
      secureFile: 'aes.pem'  # Burada Secure File olarak yüklediğiniz dosyanın ismini yazıyorsunuz

  # SSH anahtarını doğru yere yerleştirme
  - script: |
      mkdir -p ~/.ssh
      cp $(downloadSSHKey.secureFilePath) ~/.ssh/aes.pem  # Secure file'ı doğru yere kopyalıyoruz
      chmod 600 ~/.ssh/aes.pem
      ssh-keyscan -H $(remoteHost) >> ~/.ssh/known_hosts
    displayName: 'Setup SSH key'

  # Docker servisini durdurma ve yeniden başlatma
  - script: |
      ssh -o StrictHostKeyChecking=no $(remoteUser)@$(remoteHost) << 'EOF'
        sudo docker-compose down  # Docker servisini durdurma
        sudo docker-compose up -d  # Docker servisini yeniden başlatma
      EOF
    displayName: 'Restart Docker service on EC2'