trigger:
  branches:
    include:
      - main

pool:
  name: AWS  # Azure DevOps'taki agent pool'un adı

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    echo "Building the project"
    dotnet build
  displayName: 'Build Project'

- script: |
    echo "Deploying to AWS"
    ssh ec2-user@<ec2-public-ip> "cd /path/to/project && docker-compose down && docker-compose up -d"
  displayName: 'Deploy to AWS'