trigger:
- main  # Ana branch'ınız

pool:
  name: 'AWS'  # EC2 için kullanılan agent pool

variables:
  remoteUser: 'ec2-user'  # EC2 kullanıcı adı
  remoteHost: '34.243.95.209'  # EC2 IP adresi
  dockerImageName: 'kemallaydn/aes'  # Docker Hub üzerindeki imaj ismi
  dockerTag: 'latest'  # İmaj etiketi

jobs:
- job: DeployToEC2
  displayName: 'Deploy to EC2 instance'
  steps:
    # Secure file kullanarak SSH anahtarını indiriyoruz
    - task: DownloadSecureFile@1
      name: downloadSSHKey
      inputs:
        secureFile: 'aes.pem'  # Burada Secure File olarak yüklediğiniz dosyanın ismini yazıyorsunuz

    # SSH anahtarını doğru yere yerleştirme
    - script: |
        mkdir -p ~/.ssh
        cp $(downloadSSHKey.secureFilePath) ~/.ssh/id_rsa  # aes.pem dosyasını ~/.ssh/id_rsa olarak kopyalıyoruz
        chmod 600 ~/.ssh/id_rsa  # Anahtara doğru izinleri veriyoruz
        ssh-keyscan -H $(remoteHost) >> ~/.ssh/known_hosts  # EC2 sunucusunun anahtarını alıyoruz
      displayName: 'Setup SSH key'

    # EC2'de Docker imajını çekme ve çalıştırma
    - script: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $(remoteUser)@$(remoteHost) << 'EOF'
          # Docker imajını Docker Hub'dan çekme
          docker pull $(dockerImageName):$(dockerTag)
          
          # Eğer eski konteyner varsa silme
          docker ps -q --filter "name=aes-container" | grep -q . && docker stop aes-container && docker rm aes-container || echo "No existing container to stop and remove"

          # Yeni konteyneri çalıştırma
          docker run -d --name aes-container -p 8080:80 $(dockerImageName):$(dockerTag)
        EOF
      displayName: 'Deploy Docker Container on EC2'