trigger:
- main  # Ana branch'ınız (örneğin 'main' veya 'master')

pool:
  name: 'AWS'  # Agent Pool ismini burada yazıyoruz. EC2'yi eklediğimiz pool ismi bu olacak.

variables:
  remoteUser: 'ec2-user'  # EC2 kullanıcı adı
  remoteHost: '52.208.254.187'  # EC2 IP adresi
  sshKey: $(SSH_PRIVATE_KEY)  # Secure Files veya Pipeline Secrets aracılığıyla tanımladığınız SSH anahtarı

jobs:
- job: DeployToEC2
  displayName: 'Deploy to EC2 instance'
  steps:
  # SSH anahtarını doğru yere yerleştirme
  - script: |
      mkdir -p ~/.ssh
      echo "$(sshKey)" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-keyscan -H $(remoteHost) >> ~/.ssh/known_hosts
    displayName: 'Setup SSH key'

  # Docker servisini durdurma ve yeniden başlatma
  - script: |
      ssh -o StrictHostKeyChecking=no $(remoteUser)@$(remoteHost) << 'EOF'
        sudo docker-compose down  # Docker servisini durdurma
        sudo docker-compose up -d  # Docker servisini yeniden başlatma
      EOF
    displayName: 'Restart Docker service on EC2'