trigger:
- main  # Ana branch'ınız

pool:
  name: 'AWS'  # EC2 agent pool ismi

variables:
  remoteUser: 'ec2-user'  # EC2 kullanıcı adı
  remoteHost: '52.208.254.187'  # EC2 IP adresi
  sshKey: $(SSH_PRIVATE_KEY)  # Secure Files veya Pipeline Secrets aracılığıyla tanımladığınız SSH anahtarı

jobs:
- job: DeployToEC2
  displayName: 'Deploy to EC2 instance'
  steps:
  - script: |
      # SSH anahtarını ~/.ssh/id_rsa dosyasına kaydet
      mkdir -p ~/.ssh
      echo "$(sshKey)" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      # EC2 sunucusuna bağlanmadan önce anahtarın tanındığından emin olalım
      ssh-keyscan -H $(remoteHost) >> ~/.ssh/known_hosts
    displayName: 'Setup SSH key'

  - script: |
      # EC2 sunucusunda Docker servisini yeniden başlat
      ssh -o StrictHostKeyChecking=no $(remoteUser)@$(remoteHost) << 'EOF'
        sudo docker-compose down
        sudo docker-compose up -d
      EOF
    displayName: 'Restart Docker service on EC2'