name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - hikaye  # Ana branch'e commit yapıldığında çalışacak

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions, Ubuntu üzerinde çalışacak

    steps:
      # Repo'yu klonla
      - name: Checkout repository
        uses: actions/checkout@v2

      # Docker Hub'a giriş yap
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets'dan alacak
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets'dan alacak

      # Docker imajını build et
      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/aes:latest .

      # Docker imajını Docker Hub'a push et
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/aes:latest