name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Ana branch'e commit yapıldığında çalışacak

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions, Ubuntu üzerinde çalışacak

    steps:
      # Repo'yu klonla
      - name: Checkout repository
        uses: actions/checkout@v2

      # Docker Hub'a giriş yap
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets'dan alacak
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets'dan alacak

      # Docker imajını build et
      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/aes:latest .

      # Docker imajını Docker Hub'a push et
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/aes:latest

        # 5. Trigger Azure Pipeline
      - name: Trigger Azure Pipeline
        run: |
          curl -u :${{ secrets.AZURE_DEVOPS_TOKEN }} \
          -X POST \
          -H "Content-Type: application/json" \
          -d '{"definition": {"name": "kemallaydn.aes"}}' \
          https://dev.azure.com/kemalaydin3429/swapify/_apis/build/builds?api-version=6.0